;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                            ;
;                                 Keypad.inc                                 ;
;                                 EE110a HW2                                 ;
;                                 Include File                               ;
;                                                                            ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; This file contains constants used for the KeypadDemo program. 

; I/O Constants

KEYPAD_COL_0        .equ        17
KEYPAD_COL_1        .equ        18
KEYPAD_COL_2        .equ        19

DEMUX_A             .equ        
DEMUX_B             .equ        

KEYPAD_INT_MS       .equ        1       ;1ms/1KHz interrupts
